services:
  backend:
    container_name: daikoku-be
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    ports:
      - 13000:3000
    restart: always
    volumes:
      - ./backend:/app
      - be_node_modules:/app/node_modules
    tty: true
    depends_on:
      - postgres
    command:
      sh -c "yarn run start:dev"
    logging:
      driver: json-file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      NODE_ENV: development
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

  frontend:
    container_name: daikoku-fe
    build:
      context: .
      dockerfile: ./frontend.Dockerfile
    ports:
      - 15173:5173
    restart: always
    volumes:
      - ./frontend:/app
      - fe_node_modules:/app/node_modules
    tty: true
    command:
      sh -c "yarn dev --host"
    logging:
      driver: json-file
    environment:
      NODE_ENV: development

  postgres:
    container_name: daikoku-db
    image: postgres:13
    ports:
      - 15432:5432
    restart: always
    volumes:
      - check_in_daikoku_db_initdbd:/docker-entrypoint-initdb.d
      - check_in_daikoku_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

volumes:
  check_in_daikoku_db_initdbd:
  check_in_daikoku_db_data:
  be_node_modules:
  fe_node_modules:
