openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
  /api/check-in/get-current-parking:
    post:
      operationId: getCurrentParking
      summary: ''
      description: 現在地のパーキングの情報を取得する
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCurrentParkingRequest'
      responses:
        '200':
          description: 現在地のパーキングの情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parkings'
      tags: &ref_0
        - check-in
  /api/check-in:
    post:
      operationId: checkIn
      summary: ''
      description: チェックインする
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCheckInRequest'
      responses:
        '200':
          description: チェックインしたパーキングの情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParkingRoads'
      tags: *ref_0
  /api/check-in/get-user-here:
    post:
      operationId: getUserHere
      summary: ''
      description: パーキングにいるユーザを取得する
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetUserHereRequest'
      responses:
        '200':
          description: パーキングにいるユーザを取得する
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
      tags: *ref_0
  /api/close/pa-list:
    get:
      operationId: pa-list
      summary: ''
      description: パーキングエリアのリストを取得する
      parameters: []
      responses:
        '200':
          description: パーキングエリアのリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Parkings'
  /api/close/status-list:
    get:
      operationId: status-list
      summary: ''
      description: 閉鎖ステータスのリストを取得する
      parameters: []
      responses:
        '200':
          description: 閉鎖ステータスのリスト
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CloseStatuses'
  /api/close:
    post:
      operationId: post
      summary: ''
      description: 閉鎖状況を投稿する
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClosePostRequest'
      responses:
        '200':
          description: 投稿結果
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Closes'
  /api/close/status:
    get:
      operationId: status
      summary: ''
      description: 閉鎖状況を取得する
      parameters: []
      responses:
        '200':
          description: 閉鎖状況を取得する
info:
  title: Cats example
  description: The cats API description
  version: '1.0'
  contact: {}
tags:
  - name: cats
    description: ''
servers: []
components:
  schemas:
    GetCurrentParkingRequest:
      type: object
      properties:
        latitude:
          type: number
          description: 経度
          example: 35.46164868963681
        longitude:
          type: number
          description: 緯度
          example: 139.67996120452884
      required:
        - latitude
        - longitude
    CloseStatuses:
      type: object
      properties:
        id:
          type: number
          example: 1
        status:
          type: string
          example: close
        statusJpName:
          type: string
          example: 閉鎖
        close:
          type: array
          items:
            $ref: '#/components/schemas/Closes'
        createdAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
        updatedAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
      required:
        - id
        - status
        - statusJpName
        - close
        - createdAt
        - updatedAt
    Users:
      type: object
      properties:
        id:
          type: number
          example: 1
        screenName:
          type: string
          example: screenname
        name:
          type: string
          example: name
        email:
          type: string
          example: example@example.com
        password:
          type: string
          example: password
        createdAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
        updatedAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
        checkIns:
          type: array
          items:
            type: string
        close:
          type: array
          items:
            $ref: '#/components/schemas/Closes'
      required:
        - id
        - screenName
        - name
        - email
        - password
        - createdAt
        - updatedAt
        - checkIns
        - close
    Closes:
      type: object
      properties:
        id:
          type: int
          example: 1
        closeStatus:
          $ref: '#/components/schemas/CloseStatuses'
        parkingRoad:
          $ref: '#/components/schemas/ParkingRoads'
        user:
          $ref: '#/components/schemas/Users'
        createdAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
        updatedAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
      required:
        - id
        - closeStatus
        - parkingRoad
        - user
        - createdAt
        - updatedAt
    Parkings:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: 大黒PA
        latitude:
          type: number
          example: 35.46164868963681
        longitude:
          type: number
          example: 139.67996120452884
        radius:
          type: number
          example: 200
        parkingRoads:
          type: array
          items:
            $ref: '#/components/schemas/ParkingRoads'
        close:
          type: array
          items:
            $ref: '#/components/schemas/Closes'
        createdAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
        updatedAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
      required:
        - id
        - name
        - latitude
        - longitude
        - radius
        - parkingRoads
        - close
        - createdAt
        - updatedAt
    CheckIns:
      type: object
      properties:
        id:
          type: int
          example: 1
        user:
          $ref: '#/components/schemas/Users'
        parkingRoad:
          $ref: '#/components/schemas/ParkingRoads'
        createdAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
        updatedAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
      required:
        - id
        - user
        - parkingRoad
        - createdAt
        - updatedAt
    ParkingRoads:
      type: object
      properties:
        id:
          type: number
          example: 1
        parking:
          $ref: '#/components/schemas/Parkings'
        name:
          type: string
          example: 道路名
        createdAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
        updatedAt:
          type: string
          example: '2024-10-01T00:00:00.000Z'
        checkIns:
          type: array
          items:
            $ref: '#/components/schemas/CheckIns'
        closes:
          type: array
          items:
            $ref: '#/components/schemas/Closes'
      required:
        - id
        - parking
        - name
        - createdAt
        - updatedAt
        - checkIns
        - closes
    PostCheckInRequest:
      type: object
      properties:
        latitude:
          type: number
          description: 経度
          example: 35.46164868963681
        longitude:
          type: number
          description: 緯度
          example: 139.67996120452884
        userId:
          type: number
          description: ユーザID
          example: 1
        roadId:
          type: number
          description: 道路ID
          example: 1
      required:
        - latitude
        - longitude
        - userId
        - roadId
    GetUserHereRequest:
      type: object
      properties:
        parkingRoadId:
          type: number
          description: パーキング道路ID
          example: 1
      required:
        - parkingRoadId
    ClosePostRequest:
      type: object
      properties:
        parkingRoadId:
          type: number
          description: 道路ID
          example: 1
        closeStatusId:
          type: number
          description: 閉鎖ステータスID
          example: 1
        userId:
          type: number
          description: ユーザID
          example: 1
      required:
        - parkingRoadId
        - closeStatusId
        - userId
